---
title: コンパイラ エラー CS1017
ms.date: 07/20/2015
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
ms.openlocfilehash: 6371673d05ecd427dd410ea639f0f0671f851697
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/23/2019
ms.locfileid: "61654016"
---
# <a name="compiler-error-cs1017"></a><span data-ttu-id="aa36d-102">コンパイラ エラー CS1017</span><span class="sxs-lookup"><span data-stu-id="aa36d-102">Compiler Error CS1017</span></span>
<span data-ttu-id="aa36d-103">catch 句を、try ステートメントの一般的な catch 句の後に置くことはできません。</span><span class="sxs-lookup"><span data-stu-id="aa36d-103">Catch clauses cannot follow the general catch clause of a try statement</span></span>  
  
 <span data-ttu-id="aa36d-104">パラメーターを一切受け取らない `catch` ブロックは、一連の `catch` ブロックの最後に配置する必要があります。</span><span class="sxs-lookup"><span data-stu-id="aa36d-104">A `catch` block that does not take any parameters must be the last in a series of `catch` blocks.</span></span> <span data-ttu-id="aa36d-105">例外の詳細については、「 [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md)」を参照してください。</span><span class="sxs-lookup"><span data-stu-id="aa36d-105">For more information on exceptions, see [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="aa36d-106">例</span><span class="sxs-lookup"><span data-stu-id="aa36d-106">Example</span></span>  
 <span data-ttu-id="aa36d-107">次の例では CS1017 が生成されます。</span><span class="sxs-lookup"><span data-stu-id="aa36d-107">The following sample generates CS1017:</span></span>  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
