---
title: "コンパイラ エラー CS1017"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: adfebf5f696090aa7355025e4c2cba2240e1a6c3
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs1017"></a>コンパイラ エラー CS1017
catch 句を、try ステートメントの一般的な catch 句の後に置くことはできません。  
  
 パラメーターを一切受け取らない `catch` ブロックは、一連の `catch` ブロックの最後に配置する必要があります。 例外の詳細については、「 [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md)」を参照してください。  
  
## <a name="example"></a>例  
 次の例では CS1017 が生成されます。  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
