---
title: "エンドポイント : 失敗した呼び出し"
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: 3bdca983-7199-4596-b7e1-de15c0766250
caps.latest.revision: "5"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.workload: dotnet
ms.openlocfilehash: 2ec0cd00ed4dc3f873d006133421784b9be00837
ms.sourcegitcommit: 16186c34a957fdd52e5db7294f291f7530ac9d24
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 12/22/2017
---
# <a name="endpoint-calls-failed"></a>エンドポイント : 失敗した呼び出し
カウンター名 : 失敗した呼び出し。  
  
## <a name="description"></a>説明  
 このエンドポイントで処理できない例外が発生した呼び出しの数です。 このカウンターは、このエンドポイントで未処理の例外が発生するたびにインクリメントされます。  
  
## <a name="see-also"></a>参照  
 [コントラクトおよびサービスのエラーの指定と処理](../../../../../docs/framework/wcf/specifying-and-handling-faults-in-contracts-and-services.md)
