---
title: "例外処理ステートメント (C# リファレンス) | Microsoft Docs"
ms.date: "2015-07-20"
ms.prod: ".net"
ms.technology: 
  - "devlang-csharp"
ms.topic: "article"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "キーワード [C#], 例外処理"
ms.assetid: 6d0323a3-3164-411c-9b84-a3606bd0e13c
caps.latest.revision: 12
author: "BillWagner"
ms.author: "wiwagn"
caps.handback.revision: 12
---
# 例外処理ステートメント (C# リファレンス)
C\# は、プログラムの実行中に発生する例外という異常事態を処理する機構を組み込んでいます。  このような例外は、通常の制御の流れの外で処理されます。  
  
 ここでは、例外処理に関する次のトピックについて説明します。  
  
-   [throw](../../../csharp/language-reference/keywords/throw.md)  
  
-   [try\-catch](../../../csharp/language-reference/keywords/try-catch.md)  
  
-   [try\-finally](../../../csharp/language-reference/keywords/try-finally.md)  
  
-   [try\-catch\-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)  
  
## 参照  
 [C\# リファレンス](../../../csharp/language-reference/index.md)   
 [C\# プログラミング ガイド](../../../csharp/programming-guide/index.md)   
 [C\# のキーワード](../../../csharp/language-reference/keywords/index.md)   
 [ステートメントのキーワード](../../../csharp/language-reference/keywords/statement-keywords.md)   
 [例外と例外処理](../../../csharp/programming-guide/exceptions/exceptions-and-exception-handling.md)